version: '3'
services:
    std_streams:
        build: ./std_streams
        ports:
            # host:8080 <- container:8080
            - '8080:8080'
        volumes:
            - './std_streams/exec:/mount'
        networks:
            - appnet
    vnc_viewer:
        build: ./vnc_viewer
        ports:
            # host:6080 <- container:6080
            - '6080:6080'
        networks:
            - appnet
    qemu_viewer:
        build: ./qemu_viewer
        ports:
            # host:6090 <- container:6080
            - '6090:6080'
        networks:
            - appnet
networks:
    appnet:
        driver: bridge
